services:
  - type: web
    name: busdriver-api
    env: python
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT"
    plan: free
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
