services:
  - type: web
    name: busdriver-api
    env: python
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "gunicorn backend.backend.wsgi:application --bind 0.0.0.0:$PORT"
    plan: free
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.backend.settings
